@Results = new Meteor.Collection "results"
@Votes = new Meteor.Collection "votes"
@Countries = new Meteor.Collection "countries"
@Questions = new Meteor.Collection "questions"
@Gifs = new Meteor.Collection "gifs"
@Scores = new Meteor.Collection "scores"
@VoteCounts = new Meteor.Collection "voteCounts"